import { createRequire } from 'node:module'
const req = createRequire(new URL('../apps/web/package.json', import.meta.url))
const { chromium } = req('playwright')
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage()
await page.goto('http://127.0.0.1:3400/sign-up')
await page.waitForLoadState('networkidle')
const title = await page.title()
const inputs = await page.evaluate(() => [...document.querySelectorAll('input')].map(i => ({ name: i.name, type: i.type, placeholder: i.placeholder })))
const buttons = await page.evaluate(() => [...document.querySelectorAll('button')].map(b => ({ type: b.type, text: b.innerText.trim() })))
console.log('Title:', title)
console.log('Inputs:', JSON.stringify(inputs))
console.log('Buttons:', JSON.stringify(buttons))
await page.screenshot({ path: 'specs/artifacts/debug-signup.png' })
await browser.close()
